from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController
import random
import time

# ==========================================
# 🎮 SISTEMA PRINCIPAL ViNX0
# ==========================================
app = Ursina()

# Definición de tipos de bloques/geometrías (Estilo Lego/Color)
blocks = [
    color.white,       # Cubo básico
        color.orange,      # Pieza especial
            color.azure,       # Cristal
                color.rgb(255,215,0), # Oro
                    color.rgb(128,0,128)  # Élite
                    ]
                    selected_block = 0

                    # ==========================================
                    # 🏦 SISTEMA ECONÓMICO Y DE PERFILES
                    # ==========================================
                    class GlobalEcosystem:
                        def __init__(self):
                                self.users = {}
                                        self.economy_pool = 1000000
                                                print("🌐 ECOSISTEMA GLOBAL ACTIVO")

                                                    def create_profile(self, user_id, zone_theme):
                                                            self.users[user_id] = {
                                                                        "balance": 5000,  # Dinero inicial generoso
                                                                                    "level": 1,
                                                                                                "exp": 0,
                                                                                                            "inventory": [],
                                                                                                                        "zone": zone_theme,
                                                                                                                                    "insignias": ["🥉 Explorador Inicial"],
                                                                                                                                                "blocks_broken": 0,
                                                                                                                                                            "blocks_built": 0
                                                                                                                                                                    }
                                                                                                                                                                            print(f"✅ Perfil creado: {user_id} | Zona: {zone_theme} | K$H: {self.users[user_id]['balance']}")

                                                                                                                                                                                def reward_user(self, user_id, amount, reason):
                                                                                                                                                                                        if user_id in self.users:
                                                                                                                                                                                                    self.users[user_id]["balance"] += amount
                                                                                                                                                                                                                print(f"💰 +{amount} K$H | Motivo: {reason}")

                                                                                                                                                                                                                    def add_exp(self, user_id, amount):
                                                                                                                                                                                                                            self.users[user_id]["exp"] += amount
                                                                                                                                                                                                                                    if self.users[user_id]["exp"] >= 100:
                                                                                                                                                                                                                                                self.users[user_id]["level"] += 1
                                                                                                                                                                                                                                                            self.users[user_id]["exp"] = 0
                                                                                                                                                                                                                                                                        print(f"⬆️ ¡SUBISTE DE NIVEL! Nivel: {self.users[user_id]['level']}")

                                                                                                                                                                                                                                                                        # ==========================================
                                                                                                                                                                                                                                                                        # 🧠 MOTOR OMNIPOTENTE
                                                                                                                                                                                                                                                                        # ==========================================
                                                                                                                                                                                                                                                                        class OmnipotentEngine:
                                                                                                                                                                                                                                                                            def __init__(self):
                                                                                                                                                                                                                                                                                    self.metaverse_data = {
                                                                                                                                                                                                                                                                                                "status": "ONLINE",
                                                                                                                                                                                                                                                                                                            "version": "V1.0.0",
                                                                                                                                                                                                                                                                                                                        "gravity": 9.8
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                        self.ecosystem = GlobalEcosystem()
                                                                                                                                                                                                                                                                                                                                                print("⚡ ViNX0 ENGINE INITIALIZED")

                                                                                                                                                                                                                                                                                                                                                    def create_super_user(self, name, era="Futurista"):
                                                                                                                                                                                                                                                                                                                                                            self.ecosystem.create_profile(name, era)
                                                                                                                                                                                                                                                                                                                                                                    return f"👤 Usuario {name} cargado en modo {era}"

                                                                                                                                                                                                                                                                                                                                                                        def generate_ia_infrastructure(self, type="city"):
                                                                                                                                                                                                                                                                                                                                                                                print(f"🏙️ GENERANDO INFRAESTRUCTURA: {type}")
                                                                                                                                                                                                                                                                                                                                                                                        # Aquí iría la lógica para generar ciudades automáticamente
                                                                                                                                                                                                                                                                                                                                                                                                return "Geometría 8K cargada..."

                                                                                                                                                                                                                                                                                                                                                                                                # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                # 🧱 CLASE DE BLOQUES / VOXELS
                                                                                                                                                                                                                                                                                                                                                                                                # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                class Voxel(Button):
                                                                                                                                                                                                                                                                                                                                                                                                    def __init__(self, position=(0,0,0), color=color.white):
                                                                                                                                                                                                                                                                                                                                                                                                            super().__init__(
                                                                                                                                                                                                                                                                                                                                                                                                                        parent = scene,
                                                                                                                                                                                                                                                                                                                                                                                                                                    position = position,
                                                                                                                                                                                                                                                                                                                                                                                                                                                model = 'cube',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            origin_y = 0.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        texture = 'white_cube',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color = color,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                highlight_color = color.lime,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def input(self, key):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if self.hovered:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # CLICK IZQUIERDO: CREAR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if key == 'left mouse down':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Voxel(position = self.position + mouse.normal, color = blocks[selected_block])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            main_engine.ecosystem.reward_user("Admin", 5, "Construcción")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            main_engine.ecosystem.add_exp("Admin", 2)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # CLICK DERECHO: DESTRUIR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if key == 'right mouse down':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    destroy(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main_engine.ecosystem.reward_user("Admin", 2, "Recolección")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main_engine.ecosystem.add_exp("Admin", 1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 🕹️ CONTROLES Y ACTUALIZACIÓN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def update():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        global selected_block

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Cambiar bloque con teclado
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if held_keys['1']: selected_block = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if held_keys['2']: selected_block = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if held_keys['3']: selected_block = 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if held_keys['4']: selected_block = 3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if held_keys['5']: selected_block = 4

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Mostrar información en consola si presionamos TAB
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if held_keys['tab']:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data = main_engine.ecosystem.users["Admin"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"--- STATS ---")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Nivel: {data['level']}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Dinero: {data['balance']} K$H")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Insignias: {data['insignias']}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 🌄 GENERACIÓN DEL MUNDO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def generate_world(mode="NORMAL"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"🗺️ Generando mundo en modo: {mode}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for z in range(20):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for x in range(20):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Suelo base con variación
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if mode == "MOUNTAIN":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        y = random.randint(0, 5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    y = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Voxel(position=(x, y, z), color=color.rgb(100, 100, 100))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 🚀 ARRANQUE DEL SISTEMA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Inicializar Motor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main_engine = OmnipotentEngine()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main_engine.create_super_user("Admin", "NINJAGO REALM")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main_engine.generate_ia_infrastructure("Metrópolis 8K")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Generar mapa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                generate_world("NORMAL")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Configurar jugador y cámara
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                player = FirstPersonController()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Sky()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Texto en pantalla
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def ui_draw():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text(f"ViNX0 V1.0.0 | BLOQUE: {selected_block+1}", position=(-0.85, 0.45), scale=1.5, color=color.cyan)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text(f"BANCO K$H: {main_engine.ecosystem.users['Admin']['balance']}", position=(-0.85, 0.40), scale=1.2, color=color.yellow)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            text(f"NIVEL: {main_engine.ecosystem.users['Admin']['level']}", position=(-0.85, 0.35), scale=1.2, color=color.green)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.run()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from